### ISSUE TITLE
Make the distinction between host and switch clear

### ISSUE THREAD

**Issue by mattiasb** [rgl/ansible-collection-tp-link-easy-smart-switch#3]
In `plugins/modules/smrt_config.py` we can see documentation
for the input parameters to `smrt_config`:

```yaml

...

host_ip_address:
    required: True
    description:
        - The host ip address.
    type: str
host_mac_address:
    required: True
    description:
        - The host mac address.
    type: str
switch_mac_address:
    required: True
    description:
        - The switch mac address.
    type: str
...
```

It starts off pretty clear with what I assume is the
IP address and MAC address of the switch.

Then I get to `switch_mac_address` and now I don't
understand a thing anymore because if "host" is the
switch then why do we specifically talk about "The switch"
just below?

Some things I would like cleared up in the documentation
above is (I can send in a PR for this when I understand):

1. What is "host"? Is it the switch? If not then what?
2. How do I set the IP address of the switch?
